# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wase_endpoint}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Douglas F Shearer"]
  s.date = %q{2009-11-05}
  s.description = %q{WaseEndpoint is a library for building daemons that act as WASE Endpoints for http://bit.ly/3qRMbv}
  s.email = %q{dougal.s@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example/init.rb",
     "example/my_endpoint.rb",
     "example/server.rb",
     "lib/wase_endpoint.rb",
     "lib/wase_endpoint/message.rb",
     "lib/wase_endpoint/twitterer.rb",
     "spec/spec_helper.rb",
     "spec/wase_endpoint_message_spec.rb",
     "spec/wase_endpoint_spec.rb",
     "spec/wase_endpoint_twitterer_spec.rb"
  ]
  s.homepage = %q{http://github.com/dougal/wase_endpoint}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{WaseEndpoint is a library for building daemons that act as WASE Endpoints for http://bit.ly/3qRMbv}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/wase_endpoint_message_spec.rb",
     "spec/wase_endpoint_spec.rb",
     "spec/wase_endpoint_twitterer_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

